name: Dreams.Build on Grid
favicon: null
layout_spectrum: 0.11985206184908748
typography_spectrum: 0.8863202752545476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1438993241172284
  lightness: 0.587405824335292
  saturation: 0.9038405457977206
  rhythmicContrast: 0.3807764002121985
purpose: []
