name: Dreams.Build on Grid
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Dreams.Build
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#55bbd6'
    - '#585858'
    - '#000000'
    - '#909090'
  brandStrength: 0.1438993241172284
  lightness: 0.587405824335292
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
